Title = "BCUwDTW ZSPZD"

baseURL = 'https://bcu.zspzd-technikum.pl/'
theme = "theme1"
languageCode = 'pl-pl'

[params]
subtitle1 = "Branżowe Centrum Umiejętności"
subtitle2 = "w dziedzinie Technika Weterynaryjna"
subtitle3 = "w Zespole Szkół Centrum Kształcenia Rolniczego"
subtitle4 = "Imienia Jadwigi Dziubińskiej"
subtitle5 = "w Zduńskiej Dąbrowie"

[module]
[module.hugoVersion]
min = "0.92.0"

[[module.imports]]
path="github.com/gohugoio/hugo-mod-bootstrap-scss/v5"

[menu]
[[menu.main]]
identifier = "project"
name = "Projekt"
url  = "/#project"
weight = 10
[[menu.main]]
identifier = "location"
name = "Lokalizacja"
url  = "/#location"
weight = 20
[[menu.main]]
identifier = "contact"
name = "Kontakt"
url  = "/#contact"
weight = 30
[[menu.main]]
identifier = "news"
name = "Aktualności"
pageref  = "/posts/"
weight = 40